language: python
python:
  - '2.6'
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.8'
  - '3.9'
install:
    - pip install pipenv
    - make install-dev
    - make install-package-in-venv
script:
    - make test
